### ISSUE TITLE
Score interpretation

### ISSUE THREAD

**Issue by kaisaph** [trinker/readability#5]
I'd like clarification about interpreting the scores: 

Are all the scores for reading grade (like school grade), and if yes, should I just interpret anything above 14 to be 'post-graduate' level? Please see attached example
<img width="1090" alt="example" src="https://user-images.githubusercontent.com/19817814/38507567-cbeda872-3c14-11e8-909d-eac45a21c3c6.png">

**Comment by trinker** [comment]
These look like very small texts.  Readability scores are inaccurate on very small samples.  From what you're showing here the results are not to be trusted.
